# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import expdeploy.testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=128)),
                ('docfile', models.FileField(upload_to=expdeploy.testapp.models.uuid_file_name)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('filetext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='experiment',
            field=models.ManyToManyField(to='testapp.ExperimentModel'),
        ),
    ]
