# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentfile',
            name='filetext',
            field=models.TextField(default='default text'),
            preserve_default=False,
        ),
    ]
