# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentfile',
            name='experiment',
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='experiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.ExperimentModel'),
            preserve_default=False,
        ),
    ]
