# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_experimentfile_filetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfile',
            name='docfile',
            field=models.FileField(upload_to='testapp/webfiles'),
        ),
    ]
