# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20160201_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentfile',
            name='filetext',
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='filename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
