# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20160201_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentfile',
            name='original_filename',
            field=models.CharField(default='asdfghjkl', max_length=128),
            preserve_default=False,
        ),
    ]
