# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import expdeploy.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_experimentfile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfile',
            name='docfile',
            field=models.FileField(upload_to=expdeploy.testapp.models.uuid_file_name),
        ),
    ]
