# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20160213_0002'),
        ('testapp', '0005_auto_20160212_2045'),
    ]

    operations = [
    ]
