# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='filetext',
            field=models.TextField(default=datetime.datetime(2016, 2, 13, 3, 55, 50, 199676, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
