# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='filetext',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
