# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20160213_0355'),
        ('testapp', '0007_auto_20160213_1544'),
    ]

    operations = [
    ]
