# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileloader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='staticfiles',
            new_name='attachments',
        ),
    ]
