# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileloader', '0002_auto_20160127_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='attachments',
        ),
    ]
