# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expdeploy.gpaas.models


class Migration(migrations.Migration):

    replaces = [(b'gpaas', '0001_initial'), (b'gpaas', '0002_auto_20160512_1412'), (b'gpaas', '0003_experimentmodel_hit_payment'), (b'gpaas', '0004_auto_20160512_1444'), (b'gpaas', '0005_remove_experimentmodel_hit_payment')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=expdeploy.gpaas.models.uuid_file_name)),
                ('filetext', models.TextField()),
                ('original_filename', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('hit_description', models.CharField(max_length=120)),
                ('hit_keywords', models.CharField(max_length=120)),
                ('sandbox', models.BooleanField(default=True)),
                ('n', models.IntegerField(default=5)),
                ('published', models.BooleanField(default=False)),
                ('banned', models.TextField(default='{"ids":[]}')),
                ('hitID', models.CharField(max_length=120)),
                ('bonus_payment', models.FloatField(blank=0, default=1.0)),
                ('per_task_payment', models.FloatField(blank=0.1, default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_key_id', models.CharField(max_length=250)),
                ('aws_secret_key', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpaas.ExperimentModel'),
        ),
    ]
