# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='bonus_payment',
            field=models.FloatField(blank=0, default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentmodel',
            name='per_task_payment',
            field=models.FloatField(blank=0.1, default=1.0),
            preserve_default=False,
        ),
    ]
