# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='banned',
            field=models.TextField(default='{"ids":[]}'),
        ),
    ]
