# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='hit_description',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentmodel',
            name='hit_keywords',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentmodel',
            name='hit_payment',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
