# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0002_auto_20160512_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='hit_payment',
            field=models.FloatField(blank=0.1, default=1),
            preserve_default=False,
        ),
    ]
