# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0003_auto_20160311_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='n',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='experimentmodel',
            name='sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
