# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0003_experimentmodel_hit_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='hit_payment',
            field=models.FloatField(blank=0.1, null=True),
        ),
    ]
