# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0004_auto_20160512_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentmodel',
            name='hit_payment',
        ),
    ]
