# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaas', '0005_experimentmodel_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='hitID',
            field=models.CharField(default='  ', max_length=120),
            preserve_default=False,
        ),
    ]
