# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpaas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newStatus', models.TextField(default=b'')),
                ('eventType', models.TextField(default=b'changeStatus')),
                ('timeStamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAgent', models.TextField(default=b'')),
                ('dimensions', models.TextField(default=b'')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitId', models.TextField(default=b'')),
                ('assignmentId', models.TextField(default=b'')),
                ('workerId', models.TextField(default=b'')),
                ('results', models.TextField(default=b'{"data":[], "metadata":[]}')),
                ('history', models.TextField(default=b'{"events":[] }')),
                ('params', models.TextField(default=b'PaidAssignment')),
                ('currentStatus', models.CharField(default=b'Waiting', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('researcher', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('wid', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpaas.ExperimentModel')),
                ('metaData', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Metadata')),
            ],
        ),
        migrations.AddField(
            model_name='historyevent',
            name='workerTask',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.WorkerTask'),
        ),
    ]
