# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpaas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(default=b'{}')),
                ('results', models.TextField(default=b'null')),
                ('researcher', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('wid', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpaas.ExperimentModel')),
            ],
        ),
    ]
