# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertask',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ExperimentModel'),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='params',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='results',
            field=models.TextField(default=b'null'),
        ),
    ]
