# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='trials',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
