# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160229_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertask',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ExperimentModel'),
        ),
    ]
