# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160324_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertask',
            name='currentStatus',
            field=models.CharField(default=b'Waiting', max_length=100),
        ),
        migrations.AddField(
            model_name='workertask',
            name='history',
            field=models.TextField(default=b'{"events":[] }'),
        ),
    ]
