# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historyevent_workertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertask',
            name='params',
            field=models.TextField(default=b'PaidAssignment'),
        ),
    ]
