# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historyevent_workertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertask',
            name='assignmentId',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='workertask',
            name='hitId',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='params',
            field=models.TextField(default=b'PaidAssignment'),
        ),
    ]
