# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tasks_trials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='trials',
            field=models.CharField(default='{}', max_length=10000),
        ),
    ]
