# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160425_0635'),
        ('api', '0003_auto_20160418_1321'),
    ]

    operations = [
    ]
