# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        ('api', '0003_auto_20160229_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workertask',
            name='experiment',
        ),
        migrations.AddField(
            model_name='workertask',
            name='experiment',
            field=models.ManyToManyField(to='testapp.ExperimentModel'),
        ),
    ]
