# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160201_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='experiment',
        ),
        migrations.AddField(
            model_name='experiment',
            name='data',
            field=models.CharField(default='{}', max_length=1000000),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
