# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        ('api', '0004_auto_20160229_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workertask',
            name='experiment',
        ),
        migrations.AddField(
            model_name='workertask',
            name='experiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.ExperimentModel'),
            preserve_default=False,
        ),
    ]
